Pull Request for the Completed Features of the project "Building with Backgrounds and Gradients"
adewaleK/Building-with-Backgrounds-and-Gradients pull request #2
Opened 2020-02-28 00:26 UTC by adewaleK

I have just completed all the features of my solo project on "
Building with Backgrounds and Gradients" and hereby request for a code review. All the features have been completed in the created development branch.

Thanks.

2020-02-28 01:09 UTC, addod19 requested changes
## Status: Require changes 🔴

Hi @adewaleK, 👐  you have done a great job with the project. 🙂 However, we need to fix comments below:
- Kindly enable stickler to check your files for warnings/errors if any. Check the [link](https://stickler-ci.com/) to enable a stickler for your repository.
- Kindly wrap each ```.feature#``` in the class ```.highlight``` with the ```<a>``` tag. Currently, it is the other way around.
- Kindly edit the README file. Check [template](https://github.com/microverseinc/readme-template)

Kindly make these changes and submit another code review 👍 
_Happpy coding__ 💻 
@slack => Daniel Larbi Addo

2020-02-28 01:09 UTC, addod19 commented on index.html
> +          <div class="feature4"><a href="#"></a></div>
Hi @adewaleK, 🙂  kindly wrap the ```<div>``` with the ```<a>``` so that the elements will be clickable. It should be this way => ```<a href="#"><div class="feature1"></div></a>``` 👍

2020-02-28 22:40 UTC, adewaleK commented on index.html
> +          <div class="feature4"><a href="#"></a></div>
Hi,
I have implemented the necessary changes according to your suggestion. Kindly help review my code for the second time. 
Thanks

2020-02-28 23:55 UTC, SofiBretz commented
Code under review by SofiBretz. Thanks!✨

2020-02-29 00:16 UTC, SofiBretz commented
### Changes required ♻️
### Hello 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ] Missing the 'iPhone' images section, consider follow the original page section and design.

![1](https://user-images.githubusercontent.com/42303392/75596128-f9f8f900-5a6d-11ea-95f4-1627738cc056.PNG)

![1 2](https://user-images.githubusercontent.com/42303392/75596138-0ed58c80-5a6e-11ea-9f6f-5d9840578954.PNG)

- [ ] This is a SOLO Project, are you working with your partner? please explain this situation. 

![2](https://user-images.githubusercontent.com/42303392/75596206-6116ad80-5a6e-11ea-9870-5afb41a7f911.PNG)

![2 1](https://user-images.githubusercontent.com/42303392/75596267-a20ec200-5a6e-11ea-8dad-35050b914462.PNG)

- [ ] Consider center this section, as the original page.

![3](https://user-images.githubusercontent.com/42303392/75596331-df734f80-5a6e-11ea-8b5a-ed8de2b71c60.PNG)

![3 1](https://user-images.githubusercontent.com/42303392/75596335-e601c700-5a6e-11ea-90fd-d43b6352dda2.PNG)

- [ ] Consider make the input as the original page when the user types there:

![4](https://user-images.githubusercontent.com/42303392/75596390-29f4cc00-5a6f-11ea-9ee8-94c96b624718.PNG)

![4 1](https://user-images.githubusercontent.com/42303392/75596395-2c572600-5a6f-11ea-94c4-d72c89624e18.PNG)

- [ ] Consider delete the extra text line, and made it a 'link' as the original page:

![5](https://user-images.githubusercontent.com/42303392/75596414-4e50a880-5a6f-11ea-900c-fefd2e30aa6f.PNG)




[OPTIONAL]


_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

2020-03-02 22:31 UTC, kobiyoyo requested changes
## Hi @adewaleK      ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there is one more  thing required. 
### General
- [ ] Kindly fix the icon back & give it spacing as stipulated by previous TSE
![1](https://user-images.githubusercontent.com/23278161/75724018-bdcbcf80-5cdd-11ea-8bb3-2694d8483ae5.png)


### Make changes and submit another code review request.
*Happy coding*

2020-03-03 19:18 UTC, nikasulo requested changes
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

2020-03-03 19:25 UTC, nikasulo requested changes
# Great work @adewaleK :clap: 
You have done a really great job making this! Please consider the my comment below, make the necessary changes and request another review. I wish you the very best and see you at the top! :rocket: 

#### Stickler errors
You have done very nicely, however, the stickler is missing from your project! Please include it, and remember you need to ensure that all errors it throws are appropriately addressed before you request a PR review. Please look into this, address appropriately and request another review.

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-03-03 21:15 UTC, merged

2020-03-04 04:09 UTC, majovanilla commented
# Code Review in progress 👀 by Maria Reyes

2020-03-04 04:20 UTC, majovanilla commented
Hey @adewaleK , 👋

## Good job on this project! 👍

I noticed there are still some changes 👇 you need to implement from the previous code reviews to approve this request 🔍

### Required Changes: ✍️

- Always remember to activate your repo in Stickler. I cannot see your linters working!!

- Improve your Readme file. It should include a screenshot of YOUR project, not the original one.

- You didn't center the titles on the main background as the previous TSE requested. It should look exactly like the original page. 

- You should also implement this important requirement made by the TSE. Remember your page should look exactly like the original page.
![Screenshot from 2020-03-03 22-19-05](https://user-images.githubusercontent.com/51926937/75844910-1d3ce480-5d9d-11ea-870a-b6f3ba8d0974.png)



### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Use semantic HTML in the structure of your HTML file. Favor the use of `<nav>`,  `<main>`,  `<footer>`, to enclose the elements on your file. You are already using nav and footer, just add the main tag to enclose the rest of your elements.

- Consider changing the with/height relation on the 4 bottom images so that they look proportioned.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes